[entrepreneur]
title = "플래텀 ─ Entrepreneur"
url = "https://platum.kr/entrepreneur"
entrySelector = "div.post_wrapper div.post_content_wrapper div.post_header.mixed"
titleSelector = "div.post_header_title h5 a"
linkSelector = "div.post_header_title h5 a"
contentSelector = "div.post_header.mixed"
imageSelector = "div.post_img a img"
waitUntil = "networkidle"

[startup]
title = "플래텀 ─ Startup"
url = "https://platum.kr/startup"
entrySelector = "div.post_wrapper div.post_content_wrapper div.post_header.mixed"
titleSelector = "div.post_header_title h5 a"
linkSelector = "div.post_header_title h5 a"
contentSelector = "div.post_header.mixed"
imageSelector = "div.post_img a img"
waitUntil = "networkidle"

[investment]
title = "플래텀 ─ Financing"
url = "https://platum.kr/investment"
entrySelector = "div.post_wrapper div.post_content_wrapper div.post_header.mixed"
titleSelector = "div.post_header_title h5 a"
linkSelector = "div.post_header_title h5 a"
contentSelector = "div.post_header.mixed"
imageSelector = "div.post_img a img"
waitUntil = "networkidle"

[china]
title = "플래텀 ─ China"
url = "https://platum.kr/china"
entrySelector = "div.post_wrapper div.post_content_wrapper div.post_header.mixed"
titleSelector = "div.post_header_title h5 a"
linkSelector = "div.post_header_title h5 a"
contentSelector = "div.post_header.mixed"
imageSelector = "div.post_img a img"
waitUntil = "networkidle"

[trends]
title = "플래텀 ─ Trends"
url = "https://platum.kr/trends"
entrySelector = "div.post_wrapper div.post_content_wrapper div.post_header.mixed"
titleSelector = "div.post_header_title h5 a"
linkSelector = "div.post_header_title h5 a"
contentSelector = "div.post_header.mixed"
imageSelector = "div.post_img a img"
waitUntil = "networkidle"

[workinsight]
title = "플래텀 ─ Workinsight"
url = "https://platum.kr/workinsight"
entrySelector = "div.post_wrapper div.post_content_wrapper div.post_header.mixed"
titleSelector = "div.post_header_title h5 a"
linkSelector = "div.post_header_title h5 a"
contentSelector = "div.post_header.mixed"
imageSelector = "div.post_img a img"
waitUntil = "networkidle"

[marketing]
title = "플래텀 ─ Marketing"
url = "https://platum.kr/marketing"
entrySelector = "div.post_wrapper div.post_content_wrapper div.post_header.mixed"
titleSelector = "div.post_header_title h5 a"
linkSelector = "div.post_header_title h5 a"
contentSelector = "div.post_header.mixed"
imageSelector = "div.post_img a img"
waitUntil = "networkidle"
