[startup]
title = "플래텀 ─ Startup"
url = "https://platum.kr/startup"
entrySelector = "div.post_wrapper div.post_content_wrapper div.post_header.mixed"
titleSelector = "div.post_header_title h5 a"
linkSelector = "div.post_header_title h5 a"
contentSelector = "div.post_header.mixed"
imageSelector = "div.post_img a img"
waitUntil = "networkidle"
